### ISSUE TITLE
How to feed in training data; extract relevant data

### ISSUE THREAD

**Issue by aleighbrown** [softmatterlab/DeepTrack#18]
I’m interested in using your DeepTrack framework to automate axonal trafficking analysis. I have a relatively large training set of images that have already been tracked manually. 

However, I'm having some trouble understanding from the iPython notebooks how to feed in my training data, nor how to export the files that have been tracked by DeepTrack as both images and some kind of meaningful csv output of how many particles, and their x,y positions across the time duration. 

I was unsure if it was best to open this as an issue on GitHub or an email, so I’ve done both.

**Comment by giovannivolpe** [comment]
Discussed by Skype on Friday 5 July 2019
